### ISSUE TITLE
Not setting GRAALVM_HOME

### ISSUE THREAD

**Issue by UtilFunction** [version-fox/vfox-java#1]
So far using `use graalvm` only sets `GRAALVM_HOME` but not `JAVA_HOME`

**Comment by aooohan** [comment]
You can use the latest `vfox` and install the current plugin.

**Comment by UtilFunction** [comment]
> You can use the latest `vfox` and install the current plugin.

But now it doesn't set `GRAALVM_HOME` anymore 😁

**Comment by linghengqian** [comment]
- This is certainly not reasonable behavior, I opened https://github.com/version-fox/vfox-java/issues/27 .
