### ISSUE TITLE
[BUG]: oracle jdk17 在 macbook pro m1pro 芯片上环境变量配置错误

### ISSUE THREAD

**Issue by jingbai-code** [version-fox/vfox-java#12]
**Version**
0.3.4
**OS**
macOS 14.4.1 m1pro

**Describe the bug**
oracle jdk17 在 macbook pro m1pro 芯片上环境变量配置错误
<img width="1105" alt="image" src="https://github.com/version-fox/vfox-java/assets/44402117/fc9ddf2c-57a0-490f-addc-f531a06a8907">
<img width="1105" alt="image" src="https://github.com/version-fox/vfox-java/assets/44402117/c2a6fe95-dea7-498b-92da-6e088fc4c446">

**Screenshots[optional]**

**Comment by aooohan** [comment]
插件升级到最新版本试过了吗

**Comment by jingbai-code** [comment]
1、升级 vfox 到 0.4.1
2、升级 java 插件到 0.4.2
3、卸载原来的 java@17.0.11-oracle，重新安装 java@17.0.11-oracle 后问题解决
