### ISSUE TITLE
建议请求https://api.foojay.io/disco/v3.0/packages/jdks添加lib_c_type参数

### ISSUE THREAD

**Issue by herouu** [version-fox/vfox-java#13]
在ubuntu 22.04中使用vfox install java@17.0.11+9-tem下载的jdk版本是OpenJDK17U-jdk_x64_alpine-linux_hotspot_17.0.11_9.tar.gz，无法使用。
使用jabba下载正确，https://github.com/Jabba-Team/index-generator/blob/main/src/index.js，
发现其多一个参数lib_c_type=glibc

编辑.version-fox/plugin/java/lib/foojay.lua 在请求url添加&lib_c_type=glibc后正常

完整url如下
https://api.foojay.io/disco/v3.0/packages/jdks?version=17.0.11%2B9&distribution=temurin&architecture=amd64&archive_type=tar.gz&operating_system=linux&release_status=ga&latest=available&lib_c_type=glibc

**Comment by aooohan** [comment]
有兴趣提个PR吗?  ;)
