### ISSUE TITLE
vfox use java选择后java命令报找不到JRE

### ISSUE THREAD

**Issue by Yyandong** [version-fox/vfox-java#16]
open jdk8的java -version报
Error: opening registry key 'Software\JavaSoft\Java Runtime Environment'
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.

java/current目录下没有java.dll

**Comment by LordHumphrey** [comment]
复现，现在的版本好像会把指定的sdk拷贝到`.version-fox\temp`

**Comment by cccy0** [comment]
+1  我也是这问题

**Comment by aooohan** [comment]
> 复现，现在的版本好像会把指定的sdk拷贝到.version-fox\temp

不是拷贝, 是目录链接... 不过和unix的符号连接不太一样, 区别有点大.....


flutter也这个问题. 下个版本统一修复. vfox的问题
