### ISSUE TITLE
安装完成无法检测到已经安装, 无法执行uninstall 和 use

### ISSUE THREAD

**Issue by Zhangxxl** [version-fox/vfox-java#23]
![image](https://github.com/user-attachments/assets/129bbc94-13fa-4b0d-8455-34a5e696db62)

**Comment by jan-bar** [comment]
去掉@后面的v再试试看

**Comment by Zhangxxl** [comment]
> 去掉@后面的v再试试看

去掉v可以了, 这个issues可以关闭了  list命令的输出是带v的, 而我以为list输出的version是最准确的,  这里感觉可以后续调整下, 要么都带v, 要么都不代
