### ISSUE TITLE
[BUG]: Java相同版本号无法安装不同发行版

### ISSUE THREAD

**Issue by LordHumphrey** [version-fox/vfox-java#9]
**Version**
The version you are currently using
**OS**
macOS、Linux、Windows

**Describe the bug**
Java相同版本号，以21为例子，如果安装了OpenJDK，想去切换或者安装Azul时均提示`java@21 is already installed`

**Screenshots[optional]**
![image](https://github.com/version-fox/vfox/assets/43847411/0da18edf-dc62-4402-bfa5-c039da00a953)

**Comment by aooohan** [comment]
你升级一下, 我今天刚修的.  正常来说, 除了openjdk 其他都会带后缀的.

<img width="716" alt="image" src="https://github.com/version-fox/vfox-java/assets/40265686/846ae8c6-667d-4e13-b28e-a74e614adb31">

**Comment by LordHumphrey** [comment]
![image](https://github.com/version-fox/vfox-java/assets/43847411/647057a1-1288-433b-a495-ab603185bce5)
Bellsoft的jdk似乎无法安装

**Comment by LordHumphrey** [comment]
```
vfox search java jb
vfox search java bsg
```
上面两个也提示`no available version`

**Comment by aooohan** [comment]
1.librca 不是 librce, readme写错了
2. nix 漏了.....
3. jb 我的macos x64 是有版本的
4. bsg 只支持linux

**Comment by LordHumphrey** [comment]
好吧，稍等我提个pr更新README
